version: '3'
services:
  redis-unix-socket:
    image: redis:6
    volumes:
      - ./redis/redis.conf:/opt/redis/redis.conf
      - /dev/shm:/dev/shm
    command: redis-server /opt/redis/redis.conf
    environment:
      TZ: Asia/Tokyo
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
  mongo-unix-socket:
    image: mongo:bionic
    volumes:
      - /storage/dhtfs/cluster/dht_mesh_daemon/kword_store_mongodb:/data/db
      - /dev/shm:/dev/shm
      - ./mongo/mongod.conf:/etc/mongo/mongod.conf
    environment:
      MONGO_INITDB_ROOT_USERNAME: EBWzun82iVjW
      MONGO_INITDB_ROOT_PASSWORD: RNQCeZn2aqqR
    command: --serviceExecutor adaptive --unixSocketPrefix /dev/shm --filePermissions 777
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
        reservations:
          cpus: '0.4'
          memory: 128M
